### ISSUE TITLE
Api Gateway Proxy does not return body when using HttpResponse.ok()

### ISSUE THREAD

**Issue by benorama** [agorapulse/micronaut-libraries#16]
In the starter sample repo, if I replace:

return HttpResponse.ok("Hello World");

```
String helloWorld() {
        return "Hello World";
}
```

by

```
HttpResponse helloWorld() {
        return HttpResponse.ok("Hello World");
}
```

It returns 

```
{
  "statusCode": 200,
  "headers": {}
}
```

Body is missing.

When running with local server, it works fine.

**Comment by benorama** [comment]
I guess this is linked to this in `ApiGatewayProxyHandler` :
```
if (response.body() instanceof ByteBuf) {
        ByteBuf buffer = (ByteBuf) response.body();
        byte[] bytes = new byte[buffer.readableBytes()];
        buffer.readBytes(bytes);
        responseEvent.setBody(new String(bytes));
} else if (response.body() != null) {
        throw new IllegalStateException("Body is not ByteBuf: " + response.body());
}
```

In this use case, `response.body() instanceof ByteBuf` is not true ?

**Comment by benorama** [comment]
I found a simple workaround:
`return HttpResponse.ok().body("Hello World")`
instead of 
`return HttpResponse.ok("Hello World")`

**Comment by musketyr** [comment]
I just wondered if the previous one does not set the status message but
probably not

Dne po 24. pro 2018 9:45 uživatel Benoit Hediard <notifications@github.com>
napsal:

**Comment by musketyr** [comment]
this needs to be fixed in Micronaut core, see the related PR
