### ISSUE TITLE
Make ApiGatewayProxyHandler work with existing ApplicationContext

### ISSUE THREAD

**Issue by hjander** [agorapulse/micronaut-libraries#17]
I have a scenario where i would like to embed ApiGatewayProxyHandler in another Application with an already existing ApplicationContext. It looks like it could be mostly done by providing an additional constructor with an existing ApplicationContext as parameter. I am only unsure about how to create the api_gateway_proxy Environment then.

**Comment by musketyr** [comment]
Hello, sorry for the holidays' delay. Can you please elaborate bit more? `ApiGatewayProxyHandler` doesn't make much sense to use outside AWS Lambda. For another context, you can just use Micronaut HTTP Netty server and the controllers will be discovered automatically.

**Comment by musketyr** [comment]
closing for a lack of response. feel free to reopen when you add more details to the issue.
