### ISSUE TITLE
ProjectionType for global secondary indices in DynamoDB not configurable

### ISSUE THREAD

**Issue by benkeil** [agorapulse/micronaut-libraries#38]
The `DefaultDynamoDBService` creates the global secondary indices with projections type `KEYS_ONLY`

```
2019-10-17 10:57:49,515  INFO  DefaultDynamoDBService:-2 - Creating DynamoDB GSI: {IndexName: inviteRef,KeySchema: [{AttributeName: inviteRef,KeyType: HASH}],Projection: {ProjectionType: KEYS_ONLY,},ProvisionedThroughput: {ReadCapacityUnits: 2,WriteCapacityUnits: 2}}
```

It should be configurable or at least `ALL`.

**Comment by musketyr** [comment]
the configuration is generated from `DynamoDBMapper` so you should be able to change the behaviour using `GlobalSecondaryIndex` annotation.

**Comment by benkeil** [comment]
Thanks for pointing that out, it looks like it's not possible at the moment. Such an annotation does not exists .

**Comment by musketyr** [comment]
https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-dynamodb/src/main/java/com/amazonaws/services/dynamodbv2/model/GlobalSecondaryIndex.java#L74

**Comment by benkeil** [comment]
But it's not an annotation that you can use  inside the entity to configure the table.

**Comment by musketyr** [comment]
oh, you're right. in that case, it might be difficult to get this fixed from AWS library. the only way can be to create the table manually before the library connects.
